# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc, now
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='General', max_length=100)),
                ('caption', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunSQL(
          [("INSERT INTO website_category (title, caption, updated, timestamp) VALUES ('General', 'General', '%s', '%s')" % (now(), now()))]
        ),
        migrations.CreateModel(
            name='TripFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=website.models.get_trip_pdf_path)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=website.models.get_trip_photos_path)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='trip',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='trip',
            field=models.CharField(max_length=150, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 3, 16, 20, 8, 69776, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='event',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='organization',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.AddField(
            model_name='tripphoto',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Trip'),
        ),
        migrations.AddField(
            model_name='tripfile',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
    ]
