# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_improving_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='event',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='trip',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
