# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 01:17
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_add_about_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteaboutindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
