# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160812_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='widget_top_bg',
            field=models.ImageField(default='', upload_to=website.models.get_category_bg_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
