# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 01:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_add_safety_insurance_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesafetyinsuranceindexpage',
            name='body_right',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
