# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='complementary_chaperones',
            new_name='number_students',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='how_hear',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='grade_levels',
            new_name='organization_zip',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='education_department',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='meals_to_include',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='reference_file',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='travelers',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='trip',
        ),
        migrations.AddField(
            model_name='quote',
            name='attachment',
            field=models.FileField(blank=True, default='', null=True, upload_to=website.models.get_quotes_files_path),
        ),
        migrations.AddField(
            model_name='quote',
            name='chaperones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 22, 2, 31, 28, 170809, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='destination',
            field=models.CharField(default='somewhere', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='email',
            field=models.CharField(default='test@test.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='first_name',
            field=models.CharField(default='someone', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='followup_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='last_name',
            field=models.CharField(default='someone', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='meal_to_include',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='phone_ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='trip_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='budget',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='preferred_airport',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='transportation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
