# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('website', '0006_add_safety_insurance_improve_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesafetyinsuranceindexpage',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
