# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160822_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='draft',
        ),
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 26, 3, 58, 21, 351699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=website.models.YearMonthField(max_length=10),
        ),
    ]
