# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_adding_files_to_events'),
    ]

    operations = [

        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(null=True, blank=False),
        ),
    ]
