# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_add_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetestimonialpage',
            name='trip_event',
            field=models.CharField(default='', max_length=250, verbose_name='Trip or/and Event'),
        ),
    ]
