# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 17:58
from __future__ import unicode_literals
from django.db.migrations.operations.base import Operation

from django.db import migrations, models
import django.db.models.deletion


class SluglifyOperation(Operation):
    reversible = True

    def __init__(self, name):
        self.name = name

    def state_forwards(self, app_label, state):
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.name)
        schema_editor.execute("UPDATE %s SET slug = name where slug IS NULL" % from_model._meta.db_table)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        pass

    def describe(self):
        return "Update slug %s field" % self.name

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_add_testimonials_trip_event_dield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitecategory',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='websitecategory',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='websitecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categories, unlike tags, can have a hierarchy. You might have a Trip category, and under that have children categories for International and Nacional. Totally optional.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.WebsiteCategory'),
        ),
        migrations.AddField(
            model_name='websitecategory',
            name='slug',
            field=models.SlugField(max_length=80, null=True, unique=True),
        ),
        SluglifyOperation(name='websitecategory'),
    ]
