# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_date_org_from_contact_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
