# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_add_categories_tree_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecategory',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
