# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_adding_back_date_contact_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='organization',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
