# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 18:23
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_add_categories_tree_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetestimonialpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='website.WebsiteCategory'),
        ),
    ]
