# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields
import website.fields
import website.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('website', '0012_add_use_website_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTravelGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteTravelIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', website.mixins.WebsiteMixinTravelIndexPage),
        ),
        migrations.CreateModel(
            name='WebsiteTravelPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField()),
                ('text', wagtail.wagtailcore.fields.RichTextField()),
                ('destination', models.CharField(max_length=200)),
                ('date', website.fields.YearMonthField(max_length=10)),
                ('start_location', models.CharField(default='', max_length=255)),
                ('end_location', models.CharField(default='', max_length=255)),
                ('categories', modelcluster.fields.ParentalManyToManyField(to='website.WebsiteCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='websitetravelgalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.WebsiteTravelPage'),
        ),
    ]
