# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc, now


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_adding_back_organization_contact_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='subcategory',
            field=models.ManyToManyField(to='website.Category'),
        ),
        migrations.AddField(
            model_name='trip',
            name='subcategory',
            field=models.ManyToManyField(default=1, to='website.Category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
        migrations.RunSQL(
            [(
                "INSERT INTO website_subcategory (title, caption, category_id, rank, updated, timestamp) VALUES ('General', 'General', 1, 0, '%s', '%s')" % (
                    now(), now()))]
        ),
    ]
