# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_add_travel_pages'),
    ]

    operations = [

        migrations.RunSQL('''
        drop table if exists blog_blogpagegalleryimage;
        drop table if exists blog_blogpage_categories;
        drop table if exists blog_blogpagetag;
        drop table if exists blog_blogpage;
        drop table if exists blog_blogindexpage;
        drop table if exists blog_blogtagindexpage;
        delete from auth_permission where content_type_id in (select id from django_content_type where app_label = 'blog');
        delete from django_admin_log where content_type_id in (select id from django_content_type where app_label = 'blog');
        
        delete from wagtailcore_pagerevision where page_id in (select id from wagtailcore_page where content_type_id in (select id from django_content_type where app_label = 'blog'));
        delete from wagtailcore_page where content_type_id in (select id from django_content_type where app_label = 'blog');
        delete from django_content_type where app_label = 'blog';
        delete from django_migrations where app='blog';
        ''')
    ]

