# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_refactoring_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='event',
            name='subcategories',
            field=models.ManyToManyField(default=1, to='website.Subcategory'),
        ),
        migrations.AddField(
            model_name='trip',
            name='subcategories',
            field=models.ManyToManyField(default=1, to='website.Subcategory'),
        ),
    ]
