# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_add_travel_pages'),
    ]

    operations = [

        migrations.RunSQL('''
        drop table if exists blog_blogpagegalleryimage;
        drop table if exists blog_blogpage_categories;
        drop table if exists blog_blogpagetag;
        drop table if exists blog_blogpage;
        drop table if exists blog_blogindexpage;
        drop table if exists blog_blogtagindexpage;
        ''')
    ]

