# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_refactoring_trip_event_subcats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='widget_top_bg',
            field=models.ImageField(blank=True, default='', upload_to=website.models.get_category_bg_path),
        ),
    ]
