# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 11:14
from __future__ import unicode_literals

from django.db import migrations
import website.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_adding_testimonial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetestimonialpage',
            name='date',
            field=website.fields.YearMonthField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
