# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_websitetourcollectionitempage_page_link_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetourcollectionindexpage',
            name='heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
