# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('website', '0024_websitetourcollectionindexpage_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinternalcontentpage',
            name='docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
