# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('website', '0026_auto_20170815_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecategory',
            name='page_link_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
