# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20170907_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitegetquotepage',
            name='success_text',
        ),
    ]
